// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

// Added manually

declare module "*.css" {}

declare module "*.png" {
  /**
   * A path to the PNG file
   */
  const path: `${string}.png`;
  export = path;
}

/**
 * AGT ≥ 0.6.5 side-effect-free agent entry (optional until dependency is bumped).
 * Declared so TypeScript accepts dynamic import before the published types land.
 */
declare module "automated-gameplay-transmitter/agent" {
  export {
    type AgentApi,
    type AgentComment,
    type AgentLike,
    createAgentApi,
    type SpeechState,
  } from "automated-gameplay-transmitter";
}
