name: Owner-approved auto-merge

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable:
    uses: nahcnuj/conahcnuj/.github/workflows/owner-approved-auto-merge.yml@b91e34df9b769dc0980c2990e341e7bfbcec858e
    with:
      repository: ${{ github.repository }}
      pr-number: ${{ github.event.pull_request.number }}
      head-sha: ${{ github.event.pull_request.head.sha }}
      merge-method: squash
    secrets:
      auto-merge-token: ${{ secrets.AUTO_MERGE_TOKEN }}
